name: Master Deploy

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install depenedencies
        run: sudo npm i -g @zeit/ncc typescript
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.BOT_TOKEN}}
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        run: |
          git config user.name "${{secrets.BOT_USERNAME}}"
          git config user.email "${{secrets.BOT_USERNAME}}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "[AUTO] Update generated code"
            git push
          fi

  test-defaults:
    needs: deploy-action-code
    runs-on: ubuntu-latest
    steps:
      - run: test '${{secrets.ACTIONS_STEP_DEBUG}}' == 'true'
      - uses: actions/checkout@v2.3.4
      - uses: sersoft-gmbh/running-release-tags-action@master
        with:
          tag: 1.2.3
          github-token: ${{secrets.GITHUB_TOKEN}}
          dry-run: true
        id: create-tags
      - name: Check executed commands
        run: |
          ./__test__/bin/generate_expected_commands.sh '1.2.3' true true false true false false \
            '${version} Major Release Track' \
            'This release tracks the latest ${version} major release (${version}.x.y).' \
            '${version} Minor Release Track' \
            'This release tracks the latest ${version} minor release (${version}.x).' \
          > expected.txt
          echo "${{steps.create-tags.outputs.executed-commands}}" > actual.txt
          git diff --no-index -- expected.txt actual.txt

  test-customized:
    needs: deploy-action-code
    strategy:
      matrix:
        tag: ['v1.2.3', 'v2.0.0', '3.2.7d', '12.43.1', 'x4.2.1']
        update-major: [true, false]
        update-minor: [true, false]
        skip-repo-setup: [true, false]
        create-release: [true, false]
        create-release-as-draft: [true, false]
        update-full-release: [true, false]
        release-title: ['Release ${version}']
        release-body: ['Release ${version} body ${version}']
    runs-on: ubuntu-latest
    steps:
      - run: test '${{secrets.ACTIONS_STEP_DEBUG}}' == 'true'
      - uses: actions/checkout@v2.3.4
      - uses: sersoft-gmbh/running-release-tags-action@master
        with:
          tag: ${{matrix.tag}}
          update-major: ${{matrix.update-major}}
          update-minor: ${{matrix.update-minor}}
          prefix-regex: '(v|x)?'
          suffix-regex: 'd?'
          skip-repo-setup: ${{matrix.skip-repo-setup}}
          create-release: ${{matrix.create-release}}
          create-release-as-draft: ${{matrix.create-release-as-draft}}
          major-release-title: ${{matrix.release-title}}
          major-release-body: ${{matrix.release-body}}
          minor-release-title: ${{matrix.release-title}}
          minor-release-body: ${{matrix.release-body}}
          update-full-release: ${{matrix.update-full-release}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          dry-run: true
        id: create-tags
      - name: Check executed commands
        run: |
          ./__test__/bin/generate_expected_commands.sh \
            '${{matrix.tag}}' \
            '${{matrix.update-major}}' \
            '${{matrix.update-minor}}' \
            '${{matrix.skip-repo-setup}}' \
            '${{matrix.create-release}}' \
            '${{matrix.create-release-as-draft}}' \
            '${{matrix.update-full-release}}' \
            '${{matrix.release-title}}' \
            '${{matrix.release-body}}' \
            '${{matrix.release-title}}' \
            '${{matrix.release-body}}' \
          > expected.txt
          echo '${{steps.create-tags.outputs.executed-commands}}' > actual.txt
          git diff --no-index -- expected.txt actual.txt

  test-from-env:
    needs: deploy-action-code
    strategy:
      matrix:
        tag: ['v1.2.3', 'v2.0.0', '3.2.7d', '12.43.1', 'x4.2.1']
        update-major: [true, false]
        update-minor: [true, false]
        skip-repo-setup: [true, false]
        create-release: [true, false]
        create-release-as-draft: [true, false]
        release-title: ['Release ${version}']
        release-body: ['Release ${version} body ${version}']
        update-full-release: [true, false]
    runs-on: ubuntu-latest
    steps:
      - run: test '${{secrets.ACTIONS_STEP_DEBUG}}' == 'true'
      - uses: actions/checkout@v2.3.4
      - uses: sersoft-gmbh/running-release-tags-action@master
        with:
          update-major: ${{matrix.update-major}}
          update-minor: ${{matrix.update-minor}}
          prefix-regex: '(v|x)?'
          suffix-regex: 'd?'
          skip-repo-setup: ${{matrix.skip-repo-setup}}
          create-release: ${{matrix.create-release}}
          create-release-as-draft: ${{matrix.create-release-as-draft}}
          major-release-title: ${{matrix.release-title}}
          major-release-body: ${{matrix.release-body}}
          minor-release-title: ${{matrix.release-title}}
          minor-release-body: ${{matrix.release-body}}
          update-full-release: ${{matrix.update-full-release}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          dry-run: true
        env:
          TEST_GITHUB_REF: refs/tags/${{matrix.tag}}
        id: create-tags
      - name: Check executed commands
        run: |
          ./__test__/bin/generate_expected_commands.sh \
            '${{matrix.tag}}' \
            '${{matrix.update-major}}' \
            '${{matrix.update-minor}}' \
            '${{matrix.skip-repo-setup}}' \
            '${{matrix.create-release}}' \
            '${{matrix.create-release-as-draft}}' \
            '${{matrix.update-full-release}}' \
            '${{matrix.release-title}}' \
            '${{matrix.release-body}}' \
            '${{matrix.release-title}}' \
            '${{matrix.release-body}}' \
          > expected.txt
          echo '${{steps.create-tags.outputs.executed-commands}}' > actual.txt
          git diff --no-index -- expected.txt actual.txt

  test-invalid:
    needs: deploy-action-code
    strategy:
      matrix:
        tag: ['1', '34.2', 'v3x', 'not-a-version']
    runs-on: ubuntu-latest
    steps:
      - run: test '${{secrets.ACTIONS_STEP_DEBUG}}' == 'true'
      - uses: actions/checkout@v2.3.4
      - uses: sersoft-gmbh/running-release-tags-action@master
        with:
          tag: ${{matrix.tag}}
          fail-on-non-semver-tag: false
          github-token: ${{secrets.GITHUB_TOKEN}}
          dry-run: true
        id: create-tags
      - name: Check executed commands
        run: test '${{steps.create-tags.outputs.executed-commands}}' == ''
